dataloader_args:
  batch_size: 256
  num_workers: 4
  shuffle: true
dataset_args:
  input_seq_len: 8
  num_time_steps: 300
  output_seq_len: 8
  with_pars: false
model_args:
  parameter_encoder_args: null
  time_stepping_decoder:
    embed_dim: 32
    embed_hidden_dim: 32
    input_seq_len: 8
    latent_dim: 8
    num_heads: 2
    num_layers: 3
    output_seq_len: 128
optimizer_args:
  learning_rate: 0.0005
  scheduler_args:
    max_iters: 1000
    warmup: 25
  weight_decay: 1.0e-08
train_args:
  num_epochs: 1000
  patience: 50
train_stepper_args:
  mixed_precision: false
  teacher_forcing_ratio: 0.0
  teacher_forcing_ratio_reduction: 0.7
  teacher_forcing_ratio_reduction_freq: 5000
