dataloader_args:
  batch_size: 4
  num_workers: 4
  shuffle: true
model_args:
  decoder:
    kernel_size: 3
    latent_dim: 16
    num_channels:
    - 128
    - 64
    - 32
    - 16
    - 8
    - 4
    - 2
    pars_dim: 2
    resnet: true
    space_dim: 256
    transposed: true
  encoder:
    kernel_size: 3
    latent_dim: 16
    num_channels:
    - 2
    - 4
    - 8
    - 16
    - 32
    - 64
    - 128
    resnet: true
    space_dim: 256
optimizer_args:
  learning_rate: 0.0005
  scheduler_args:
    max_iters: 2000
    warmup: 1
  weight_decay: 1.0e-08
train_args:
  num_epochs: 2000
  patience: 50
train_stepper_args:
  consistency_loss_regu: null
  latent_loss_regu: 0.001
