dataloader_args:
  batch_size: 64
  num_workers: 1
  shuffle: true
model_args:
  decoder:
    kernel_size: 5
    latent_dim: 8
    num_channels:
    - 128
    - 64
    - 32
    - 16
    - 8
    - 2
    pars_dim: 2
  encoder:
    kernel_size: 5
    latent_dim: 8
    num_channels:
    - 2
    - 8
    - 16
    - 32
    - 64
    - 128
optimizer_args:
  learning_rate: 0.005
  scheduler_args:
    max_iters: 1000
    warmup: 1
  weight_decay: 1.0e-08
train_args:
  num_epochs: 2
  patience: 50
train_stepper_args:
  include_time: true
  latent_loss_regu: 0.001
