dataloader_args:
  batch_size: 4
  num_workers: 4
  shuffle: true
model_args:
  decoder:
    kernel_size: 7
    latent_dim: 4
    num_channels:
    - 128
    - 64
    - 32
    - 16
    - 8
    - 2
    pars_dim: 2
    resnet: true
    space_dim: 256
    transposed: false
  encoder:
    kernel_size: 7
    latent_dim: 4
    num_channels:
    - 2
    - 8
    - 16
    - 32
    - 64
    - 128
    resnet: true
    space_dim: 256
optimizer_args:
  learning_rate: 0.001
  scheduler_args:
    factor: 0.9
    patience: 10
  weight_decay: 1.0e-08
train_args:
  num_epochs: 2000
  patience: 50
train_stepper_args:
  consistency_loss_regu: 0.001
  latent_loss_regu: 0.001
