dataloader_args:
  batch_size: 1
  num_workers: 4
  shuffle: true
model_args:
  decoder:
    activation: leaky_relu
    embedding_dim:
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    kernel_size: 5
    latent_dim: 8
    num_channels:
    - 128
    - 64
    - 32
    - 16
    - 8
    - 4
    - 3
    num_transformer_layers: 2
    pars_dim: 2
    resnet: true
    space_dim: 512
    transposed: true
    vit: false
  encoder:
    activation: leaky_relu
    embedding_dim:
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    kernel_size: 5
    latent_dim: 8
    num_channels:
    - 3
    - 4
    - 8
    - 16
    - 32
    - 64
    - 128
    num_transformer_layers: 2
    resnet: true
    space_dim: 512
    vit: false
optimizer_args:
  learning_rate: 0.0005
  scheduler_args:
    factor: 0.9
    patience: 10
  weight_decay: 1.0e-08
train_args:
  num_epochs: 2000
  patience: 50
train_stepper_args:
  consistency_loss_regu: 0.01
  latent_loss_regu: 0.0001
  mixed_precision: false
