basic_args:
    xmin: 0
    xmax: 1000
    num_elements: 100
    num_states: 2
    polynomial_order: 3
    polynomial_type: 'legendre'

steady_state:
    newton_params:
        solver: 'direct'
        max_newton_iter: 200
        newton_tol: 1.0e-5
        num_jacobian_reuses: 1000

numerical_flux_args:
    type: 'lax_friedrichs'
    alpha: 0.5

stabilizer_args:
    type: 'slope_limiter'
    second_derivative_upper_bound: 1.0e-8

time_integrator_args:
    type: 'implicit_euler'
    step_size: 0.05
    newton_params:
        solver: 'direct'
        max_newton_iter: 200
        newton_tol: 1.0e-5
        num_jacobian_reuses: 2500

BC_args:
    type: 'dirichlet'
    treatment: 'naive'
    state_or_flux: {'left': 'state', 'right': 'state'}
