dataloader_args:
  batch_size: 4
  num_workers: 16
  shuffle: true
model_args:
  decoder:
    activation: leaky_relu
    embedding_dim:
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    kernel_size: 5
    latent_dim: 8
    num_channels:
    - 256
    - 128
    - 64
    - 32
    - 16
    - 8
    - 4
    - 3
    pars_dim: 2
    resnet: true
    space_dim: 512
    transposed: false
    vit: true
  encoder:
    activation: leaky_relu
    embedding_dim:
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    - 64
    kernel_size: 5
    latent_dim: 8
    num_channels:
    - 3
    - 4
    - 8
    - 16
    - 32
    - 64
    - 128
    - 256
    resnet: true
    space_dim: 512
    vit: true
optimizer_args:
  learning_rate: 0.001
  scheduler_args:
    factor: 0.9
    patience: 10
  weight_decay: 1.0e-08
train_args:
  num_epochs: 2000
  patience: 50
train_stepper_args:
  consistency_loss_regu: 0.001
  latent_loss_regu: 0.001
  mixed_precision: false
