dataloader_args:
  batch_size: 4
  num_workers: 8
  shuffle: true
model_args:
  decoder:
    activation: tanh
    kernel_size: 5
    latent_dim: 4
    num_channels:
    - 128
    - 64
    - 32
    - 16
    - 8
    - 2
    pars_dim: 2
    resnet: false
    space_dim: 256
    transposed: true
    vit: true
  encoder:
    activation: tanh
    kernel_size: 5
    latent_dim: 4
    num_channels:
    - 2
    - 8
    - 16
    - 32
    - 64
    - 128
    resnet: false
    space_dim: 256
    vit: true
optimizer_args:
  learning_rate: 0.0005
  scheduler_args:
    factor: 0.9
    patience: 20
  weight_decay: 1.0e-08
train_args:
  num_epochs: 2000
  patience: 50
train_stepper_args:
  consistency_loss_regu: 0.001
  latent_loss_regu: 0.001
  mixed_precision: true
