dataloader_args:
  batch_size: 256
  num_workers: 4
  shuffle: true
dataset_args:
  input_seq_len: 64
  num_time_steps: 8000
  output_seq_len: 32
model_args:
  parameter_encoder_args:
    embed_dim: 32
    embed_hidden_dim: 64
    num_heads: 2
    num_layers: 2
    pars_dim: 1
  time_stepping_decoder:
    embed_dim: 32
    embed_hidden_dim: 64
    input_seq_len: 64
    latent_dim: 16
    num_heads: 4
    num_layers: 3
    output_seq_len: 16
optimizer_args:
  learning_rate: 0.0005
  scheduler_args:
    max_iters: 1000
    warmup: 25
  weight_decay: 1.0e-08
train_args:
  num_epochs: 1000
  patience: 50
train_stepper_args:
  mixed_precision: false
  teacher_forcing_ratio: 0.0
  teacher_forcing_ratio_reduction: 1.0
  teacher_forcing_ratio_reduction_freq: 10000
