dataloader_args:
  batch_size: 4
  shuffle: True
  num_workers: 4
  
model_args:
  encoder:
    num_channels: [1, 2, 4, 8, 16, 32] #[2, 4, 8, 16, 32, 64] # 
    kernel_size: 7
    latent_dim: 16
    space_dim: 256
    resnet: False
    activation: leaky_relu
    vit: True
    embedding_dim: [32, 32, 32, 32, 32]
    num_transformer_layers: 1
  decoder:
    num_channels: [32, 16, 8, 4, 2, 1] #[64, 32, 16, 8, 4, 2] # 
    kernel_size: 7
    latent_dim: 16
    pars_dim: null
    space_dim: 256
    resnet: False
    transposed: False
    activation: leaky_relu
    vit: True
    embedding_dim: [32, 32, 32, 32, 32]
    num_transformer_layers: 1
    #padding_mode: periodic

optimizer_args:
  learning_rate: 1.0e-4
  weight_decay: 1.0e-10
  scheduler_args:
    factor: 0.9
    patience: 10

train_stepper_args:
  latent_loss_regu: 1.0e-4
  consistency_loss_regu: 1.0e-2
  mixed_precision: False

train_args:
  num_epochs: 2000
  patience: 50
