dataloader_args:
  batch_size: 4
  shuffle: True
  num_workers: 4
  
model_args:
  encoder:
    num_channels: [1, 8, 16, 32, 64, 128] #[2, 4, 8, 16, 32, 64] # 
    kernel_size: 5
    latent_dim: 12
    space_dim: 128
    resnet: False
    activation: leaky_relu
    vit: True
    embedding_dim: [128, 128, 128, 128, 128]
    num_transformer_layers: 1
  decoder:
    num_channels: [128, 64, 32, 16, 8, 1] #[64, 32, 16, 8, 4, 2] # 
    kernel_size: 5
    latent_dim: 12
    pars_dim: 1
    space_dim: 128
    resnet: False
    transposed: False
    activation: leaky_relu
    vit: True
    embedding_dim: [128, 128, 128, 128, 128]
    num_transformer_layers: 1

optimizer_args:
  learning_rate: 5.0e-4
  weight_decay: 1.0e-8
  scheduler_args:
    factor: 0.9
    patience: 10

train_stepper_args:
  latent_loss_regu: 1.0e-3
  consistency_loss_regu: 1.0e-3
  mixed_precision: False

train_args:
  num_epochs: 2000
  patience: 50
