dataloader_args:
  batch_size: 4
  shuffle: True
  num_workers: 16
  
model_args:
  encoder:
    num_channels: [3, 4, 8, 16, 32, 64, 128] #[2, 4, 8, 16, 32, 64] # 
    kernel_size: 5
    latent_dim: 8
    space_dim: 512
    resnet: True
    activation: leaky_relu
    vit: False
    embedding_dim: [64, 64, 64, 64, 64, 64]
    num_transformer_layers: 2
  decoder:
    num_channels: [128, 64, 32, 16, 8, 4, 3] #[64, 32, 16, 8, 4, 2] # 
    kernel_size: 5
    latent_dim: 8
    pars_dim: 2
    space_dim: 512
    resnet: True
    transposed: True
    activation: leaky_relu
    vit: False
    embedding_dim: [64, 64, 64, 64, 64, 64]
    num_transformer_layers: 2
    
optimizer_args:
  learning_rate: 5.0e-4
  weight_decay: 1.0e-8
  scheduler_args:
    factor: 0.9
    patience: 10

train_stepper_args:
  latent_loss_regu: 1.0e-4
  consistency_loss_regu: 1.0e-2
  mixed_precision: False

train_args:
  num_epochs: 2000
  patience: 50
