dataset_args:
  input_seq_len: 32
  output_seq_len: 32
  num_time_steps: 1000

dataloader_args:
  batch_size: 2
  shuffle: True
  num_workers: 4
  
model_args:
  num_modes: 32
  num_channels: 128
  space_dim: 512
  num_states: 3
  num_pars: 2

optimizer_args:
  learning_rate: 1.0e-4
  weight_decay: null
  scheduler_args:
    warmup: 50
    max_iters: 1000

train_stepper_args:
  teacher_forcing_ratio: 0.0
  teacher_forcing_ratio_reduction: 0.9
  teacher_forcing_ratio_reduction_freq: 50
  mixed_precision: False

train_args:
  num_epochs: 1000
  patience: 100

