dataloader_args:
  batch_size: 4
  shuffle: True
  num_workers: 4
  
model_args:
  encoder:
    num_channels: [2, 8, 16, 32, 64, 128]
    kernel_size: 7
    latent_dim: 4
    space_dim: 256
    resnet: True
  decoder:
    num_channels: [128, 64, 32, 16, 8, 2]
    kernel_size: 7
    latent_dim: 4
    pars_dim: 2
    space_dim: 256
    resnet: True
    transposed: False

optimizer_args:
  learning_rate: 1.0e-3
  weight_decay: 1.0e-8
  scheduler_args:
    factor: 0.9
    patience: 10

train_stepper_args:
  latent_loss_regu: 1.0e-3
  consistency_loss_regu: 1.0e-3

train_args:
  num_epochs: 2000
  patience: 50
