dataloader_args:
  batch_size: 4
  shuffle: True
  num_workers: 1
  
model_args:
  encoder:
    num_channels: [2, 8, 16, 32, 64, 128]
    kernel_size: 5
    latent_dim: 16
  decoder:
    num_channels: [128, 64, 32, 16, 8, 2]
    kernel_size: 5
    latent_dim: 16
    pars_dim: 2

optimizer_args:
  learning_rate: 5.0e-4
  weight_decay: 1.0e-8
  scheduler_args:
    warmup: 1
    max_iters: 2000

train_stepper_args:
  latent_loss_regu: 1.0e-3
  consistency_loss_regu: 1.0e-3

train_args:
  num_epochs: 2000
  patience: 50
