dataloader_args:
  batch_size: 4
  shuffle: True
  num_workers: 8
  
model_args:
  encoder:
    num_channels: [2, 4, 8, 16, 32, 64] #[2, 4, 8, 16, 32, 64, 128]
    kernel_size: 5
    latent_dim: 8
    space_dim: 256
    resnet: False
    activation: leaky_relu
    vit: True
    embedding_dim: [32, 32, 32, 32, 32, 32]
    num_transformer_layers: 1
  decoder:
    num_channels: [64, 32, 16, 8, 4, 2] #[128, 64, 32, 16, 8, 4, 2]
    kernel_size: 5
    latent_dim: 8
    pars_dim: 2
    space_dim: 256
    resnet: False
    transposed: False
    vit: True
    activation: leaky_relu
    embedding_dim: [32, 32, 32, 32, 32, 32]
    num_transformer_layers: 1
    
optimizer_args:
  learning_rate: 5.0e-4
  weight_decay: 1.0e-8
  scheduler_args:
    factor: 0.9
    patience: 20

train_stepper_args:
  latent_loss_regu: 1.0e-4
  consistency_loss_regu: 1.0e-3
  mixed_precision: True

train_args:
  num_epochs: 2000
  patience: 50
