dataloader_args:
  batch_size: 512
  shuffle: True
  num_workers: 4
  include_time: True
  num_skip_steps: 4
  
model_args:
  encoder:
    num_channels: [2, 8, 16, 32, 64, 128]
    kernel_size: 5
    latent_dim: 16
  decoder:
    num_channels: [128, 64, 32, 16, 8, 2]
    kernel_size: 5
    latent_dim: 16
    pars_dim: 2

optimizer_args:
  learning_rate: 5.0e-3
  weight_decay: 1.0e-8
  scheduler_args:
    warmup: 1
    max_iters: 1000

train_stepper_args:
  include_time: True

train_args:
  num_epochs: 1000
  patience: 50
