dataloader_args:
  batch_size: 128
  shuffle: True
  num_workers: 2
  input_seq_len: 4
  output_seq_len: 8
  
model_args:
  parameter_encoder_args: 
    embed_dim: 16
    num_heads: 4
    embed_hidden_dim: 16
    num_layers: 2
    pars_dim: 2
    input_seq_len: 4
  time_stepping_decoder:
    latent_dim: 16
    embed_dim: 16
    num_heads: 4
    embed_hidden_dim: 32
    num_layers: 2
    input_seq_len: 4
    output_seq_len: 8



optimizer_args:
  learning_rate: 1.0e-3
  weight_decay: 1.0e-8
  scheduler_args:
    warmup: 10
    max_iters: 50

train_stepper_args:
  teacher_forcing_ratio: 0.9
  teacher_forcing_ratio_reduction: 0.9
  teacher_forcing_ratio_reduction_freq: 5


train_args:
  num_epochs: 50

