dataloader_args:
  batch_size: 256
  shuffle: True
  num_workers: 2
  max_seq_len: 64
  
model_args:
  parameter_encoder_args: 
    embed_dim: 32
    num_heads: 2
    embed_hidden_dim: 32
    num_layers: 1
    pars_dim: 2
  time_stepping_decoder:
    latent_dim: 16
    embed_dim: 32
    num_heads: 2
    embed_hidden_dim: 32
    num_layers: 2
    max_seq_len: 64

optimizer_args:
  learning_rate: 5.0e-3
  weight_decay: 1.0e-8
  scheduler_args:
    warmup: 25
    max_iters: 200

train_stepper_args:
  teacher_forcing_ratio: 1.0
  teacher_forcing_ratio_reduction: 0.99
  teacher_forcing_ratio_reduction_freq: 10000

train_args:
  num_epochs: 200
  patience: 10

