dataloader_args:
  batch_size: 256
  shuffle: True
  num_workers: 2
  input_seq_len: 8
  output_seq_len: 16
  
model_args:
  parameter_encoder_args: 
    embed_dim: 32
    num_heads: 1
    embed_hidden_dim: 32
    num_layers: 2
    pars_dim: 2
    input_seq_len: 8
  time_stepping_decoder:
    latent_dim: 16
    embed_dim: 32
    num_heads: 1
    embed_hidden_dim: 32
    num_layers: 3
    input_seq_len: 8
    output_seq_len: 16

optimizer_args:
  learning_rate: 5.0e-3
  weight_decay: 1.0e-8
  scheduler_args:
    warmup: 15
    max_iters: 100

train_stepper_args:
  teacher_forcing_ratio: 1.0
  teacher_forcing_ratio_reduction: 0.99
  teacher_forcing_ratio_reduction_freq: 1

train_args:
  num_epochs: 100
  patience: 10

