dataloader_args:
  batch_size: 256
  shuffle: True
  num_workers: 4
  
model_args:
  encoder:
    num_channels: [2, 4, 8, 16, 32, 64]
    kernel_size: 3
    latent_dim: 16
  decoder:
    num_channels: [64, 32, 16, 8, 4, 2]
    kernel_size: 3
    latent_dim: 16
    pars_dim: 2

optimizer_args:
  learning_rate: 5.0e-3
  weight_decay: 1.0e-8

train_stepper_args:
  latent_loss_regu: 1.0e-2

train_args:
  num_epochs: 100
  patience: 10
