dataloader_args:
  batch_size: 128
  shuffle: True
  num_workers: 4
  include_time: True
  
model_args:
  encoder:
    num_channels: [2, 4, 4, 8, 8, 16, 16]
    kernel_size: 3
    latent_dim: 16
  decoder:
    num_channels: [16, 16, 8, 8, 4, 4, 2]
    kernel_size: 3
    latent_dim: 16
    pars_dim: 2

optimizer_args:
  learning_rate: 1.0e-3
  weight_decay: 1.0e-8
  scheduler_args:
    warmup: 1
    max_iters: 200

train_stepper_args:
  latent_loss_regu: 1.0e-2
  include_time: True

train_args:
  num_epochs: 100
  patience: 10
