dataloader_args:
  batch_size: 512
  num_workers: 8
  shuffle: true
dataset_args:
  input_seq_len: 16
  num_time_steps: 600
  output_seq_len: 64
model_args:
  parameter_encoder_args:
    embed_dim: 16
    embed_hidden_dim: 32
    num_heads: 2
    num_layers: 2
    pars_dim: 2
  time_stepping_decoder:
    embed_dim: 16
    embed_hidden_dim: 32
    input_seq_len: 16
    latent_dim: 4
    num_heads: 2
    num_layers: 2
    output_seq_len: 64
optimizer_args:
  learning_rate: 0.0005
  scheduler_args:
    max_iters: 1000
    warmup: 50
  weight_decay: 1.0e-10
train_args:
  num_epochs: 1000
  patience: 100
train_stepper_args:
  mixed_precision: false
  teacher_forcing_ratio: 0.0
  teacher_forcing_ratio_reduction: 0.9
  teacher_forcing_ratio_reduction_freq: 50
