dataloader_args:
  batch_size: 1024
  num_workers: 4
  shuffle: true
dataset_args:
  input_seq_len: 16
  output_seq_len: 32
model_args:
  parameter_encoder_args:
    embed_dim: 16
    embed_hidden_dim: 32
    num_heads: 2
    num_layers: 2
    pars_dim: 2
  time_stepping_decoder:
    embed_dim: 16
    embed_hidden_dim: 32
    input_seq_len: 16
    latent_dim: 16
    num_heads: 4
    num_layers: 4
    output_seq_len: 32
optimizer_args:
  learning_rate: 0.00075
  scheduler_args:
    max_iters: 1000
    warmup: 25
  weight_decay: 1.0e-06
train_args:
  num_epochs: 1000
  patience: 100
train_stepper_args:
  mixed_precision: true
  teacher_forcing_ratio: 1.0
  teacher_forcing_ratio_reduction: 0.95
  teacher_forcing_ratio_reduction_freq: 5
